getgenv().Config = {
    ["AutoReplay"] = true,
    ["AutoJoinMatch"] = true,
    ["TPLobbyIfPlayer"] = true,
    ["AutoVoteDifficulty"] = "true",
    ["AutoJoinEndless"] = true,
    ["SelectMacro"] = "pvdh",
    ["AutoSkip"] = true,
    ["DeleteMap"] = true,
    ["PlayMacro"] = true,
    ["AutoSave"] = true,
    ["BoostFPS"] = true,
    ["AutoClaimQuest"] = true,
    ["WhiteScreen"] = true,
    ["DelayJoin"] = "5",
    ["PlacingFailsafe"] = true,
    ["WebhookURL"] = "https://discord.com/api/webhooks/1207677192859942958/p79RWeRdSdutJN6Cd2So4VEt_iNYcFhp01I6kup2lncFPZZ9OlEE2ZjorCw-0oJA24an",
    ["WH_MatchComplete"] = true,
}
loadstring(game:HttpGet("https://nousigi.com/loader.lua"))()
